### ISSUE TITLE
Why is the container so large?

### ISSUE THREAD

**Issue by tomck** [vassilvk/readthedocs-docker#5]
vassilvk/readthedocs 2.297 GB

That's pretty big isn't it? Is there a way this could be trimmed a bit?

**Comment by vassilvk** [comment]
Yes - the image is huge because of all the latex packages required to provide full latex and PDF support as seen in readthedocs.org.
As I was building and testing the image, new package requirements popped up.
Here's the list of packages that made the image mushroom to 2GB+:
- texlive-latex-recommended
- texlive-fonts-recommended
- texlive-latex-extra
- doxygen
